game15/is-solvable/game15.py: ValueError exception catch
tests/NO_9.dat was causing the following traceback, because we did not handle
not-a-number values yet:

Traceback (most recent call last):
  File "./game15.py", line 102, in <module>
    g.load()
  File "./game15.py", line 21, in load
    self.board.append([int(n) for n in line.split()])
ValueError: invalid literal for int() with base 10: 'x'